import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import HeaderComponent from '@/components/header'

import '../styles/globals.css'
import FooterComponent from '@/components/footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="page-layout">
          <div className="content">{children}</div>
        </div>
      </body>
    </html>
  )
}
